apiVersion: v1
kind: Secret
metadata:
  name: octa-app-secret
  namespace: staging
type: Opaque
stringData:
  DATABASE_HOST: "REPLACE_WITH_RDS_ENDPOINT"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "REPLACE_WITH_DATABASE_NAME"
  DATABASE_USER: "REPLACE_WITH_DATABASE_USER"
  DATABASE_PASSWORD: "REPLACE_WITH_DATABASE_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_REDIS_PASSWORD"

